---
title: "ShinyNLP"
author: "Marvin Jakobs"
date: "2023-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# get needed packages
library(shiny)
library(tesseract)
library(magick)
library(stringr)

# making the ui for shiny app
ui <- fluidPage(
  titlePanel("Image to Text Converter, Black Text on White Background"),
  sidebarLayout(
    sidebarPanel(
      fileInput("image_upload", "Upload image")
      ),
    mainPanel(
      verbatimTextOutput("text_output")
    )
  )
)

# set server for the shiny app
server <- function(input, output) {
  
  # when image uploaded, read it in and convert it to text, dont preform if no file uploaded
  text_output <- reactive({
    if (is.null(input$image_upload)) { return(NULL) }
    
    # read in image
    image <- image_read(input$image_upload$datapath)
    
    # convert image to grayscale and make binary
    image <- image_convert(image, colorspace = "gray")
    image <- image_threshold(image, "white") # setting to black text on white background
    
    # using tesseract convert the image to text
    text <- ocr(image)
    
    # clean up the text if messy
    text <- str_trim(text)
    text <- str_replace_all(text, "[\r\n\t]", " ")
    text <- str_replace_all(text, " +", " ")
    
    # return text
    return(text)})
  
  # display text
  output$text_output <- renderPrint({
    text_output()})
}

# run shiny app
shinyApp(ui, server)
```
